### ISSUE TITLE
Goodscents duplicates

### ISSUE THREAD

**Issue by joelmainland** [pyrfume/pyrfume-data#98]
I haven't done a deep dive on this, but there are some conflicts in Goodscents. CID 58 (TGSC.ID 1037661) is duplicated. CID 126 (TGSC.ID 1040191) is present twice, but the "brown" label is different in the two entries.

**Comment by rgerkin** [comment]
@joelmainland This is one of the ones contributed externally.  It's possible an error was introduced in my standardization, or it could be in the contributed files.  Because it is also one of the largest, it may be challenging to fully audit it before game time.

**Comment by contrebande-labs** [comment]
The duplicates are part of the original TGSC dataset. We chose not to filter them as stated in the dataset README because they have different TGSC Ids and the profiles contain complementary data. But maybe the Pyrfume index could be deduped by other identifiers, pubchem or otherwise.

**Comment by SimonEnsemble** [comment]
I just discovered this too! I imagine this unexpected attribute of the data could cause errors in analyses... (as it almost did mine!)

`goodscents/behaviors_sparse.csv` has duplicate rows for a given molecule, but the list of tags are different. the `behavior.csv` file is the same in terms of duplicated molecules among rows.

feel like a warning should at least be printed when folks query this file?
```python
import pyrfume
pyrfume.load_data('goodscents/behavior_sparse.csv') # prints warning
```

**Comment by rgerkin** [comment]
Fixed in #176

**Comment by SimonEnsemble** [comment]
now on `pyrfume` Version: 0.18.1.

still getting duplicate molecules on "goodscents", after I:
* read in `behavior.csv`, `stimuli.csv`, and `molecules.csv`.
* join `behaviors.csv` and `stimuli.csv` on the `"Stimulus"` column (via `behavior_w_id = innerjoin(behaviors, stimuli, on="Stimulus")` in Julia)
* finally, inner-join this table with the molecules table on the `"CID"` column (`goodscents = innerjoin(behavior_w_id, molecules, on="CID")` in Julia)
I get `4626` rows in `goodscents` after this, but only `4565` unique SMILES strings.

e.g. the SMILES string `CC(=O)OC(C)(C)CCCC(=C)C=C` is duplicated. I found that this molecule has the same `CID=14235` but two different `TGSC ID = 1004301,1017191` in the `stimulus` table. weird.

<img width="837" alt="Screen Shot 2022-10-19 at 6 53 54 PM" src="https://user-images.githubusercontent.com/30643894/196837681-a362d21c-8768-4a78-9302-5534cfdc7e23.png">

**Comment by rgerkin** [comment]
We had three options here:
1. Keep both entries for a given CID and produce the behavior you observe.
2. Pick one as best and drop the other.
3. Merge them according to the union or intersection of the descriptors.

We chose 1 as it is the least opinionated and leaves the researcher the flexibility to implement 2 or 3 as a next step.

**Comment by SimonEnsemble** [comment]
very reasonable to me, thanks for explaining! 😄 
[I will take the union.]
PS I hope I never encounter this molecule in the Goodscents data set! 😆 
<img width="837" alt="Screen Shot 2022-10-19 at 8 52 04 PM" src="https://user-images.githubusercontent.com/30643894/196852422-23f6245b-6a4d-4396-b3dc-72a5793689a2.png">

**Comment by rgerkin** [comment]
Try this one! https://en.m.wikipedia.org/wiki/Thioacetone
